import torch
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv, GATv2Conv
from torch_geometric.data import Data
import pandas as pd
import os
import argparse
from sklearn.metrics import accuracy_score, f1_score, classification_report
import time

OUTPUT_DIR = r"d:\Capstone\fnd\outputs"

class GraphSAGEModel(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, dropout=0.3):
        super(GraphSAGEModel, self).__init__()
        # GraphSAGE computes node representations by aggregating features from neighbors
        self.conv1 = SAGEConv(in_channels, hidden_channels)
        self.conv2 = SAGEConv(hidden_channels, out_channels)
        self.dropout = dropout

    def forward(self, x, edge_index):
        # Layer 1
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)
        
        # Layer 2 (Classification Head)
        x = self.conv2(x, edge_index)
        return x

class GATv2Model(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=4, dropout=0.3):
        super(GATv2Model, self).__init__()
        # GATv2 uses an attention mechanism to assign different importance weights 
        # to different neighbors, rather than just averaging them like GraphSAGE.
        # We use multiple attention 'heads' for better representation learning.
        self.conv1 = GATv2Conv(in_channels, hidden_channels, heads=heads, dropout=dropout)
        # The output of conv1 is concatenated across heads, so in_channels for conv2 = hidden_channels * heads
        self.conv2 = GATv2Conv(hidden_channels * heads, out_channels, heads=1, concat=False, dropout=dropout)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.conv1(x, edge_index)
        x = F.elu(x)
        
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.conv2(x, edge_index)
        return x

def load_graph_data():
    print("Loading Graph and Node Features...")
    # 1. Load Edge Index
    edge_index = torch.load(os.path.join(OUTPUT_DIR, "graphs", "edge_index.pt"))
    
    # 2. Load Node Embeddings (Generated by DistilBERT)
    x = torch.load(os.path.join(OUTPUT_DIR, "embeddings", "node_embeddings.pt"))
    
    # 3. Load Node Mapping (to get labels and splits)
    mapping = pd.read_csv(os.path.join(OUTPUT_DIR, "graphs", "node_mapping.csv"))
    
    # Create Labels tensor (ignoring NaNs from any unlabeled data)
    y = torch.tensor(mapping['label'].values, dtype=torch.long)
    
    # Create boolean masks for train/val/test splits to prevent label leakage
    train_mask = torch.tensor((mapping['split'] == 'train').values, dtype=torch.bool)
    val_mask = torch.tensor((mapping['split'] == 'val').values, dtype=torch.bool)
    test_mask = torch.tensor((mapping['split'] == 'test').values, dtype=torch.bool)
    
    # Wrap in a PyTorch Geometric Data object
    data = Data(x=x, edge_index=edge_index, y=y, train_mask=train_mask, val_mask=val_mask, test_mask=test_mask)
    return data

def train_gnn(model_type="graphsage"):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    data = load_graph_data().to(device)
    print(f"Graph loaded: {data.num_nodes} nodes, {data.num_edges} edges.")
    
    # Model Setup
    in_channels = data.x.size(1) # Should be 768 from DistilBERT
    hidden_channels = 64
    out_channels = 2 # Binary classification (Real vs Fake)
    
    if model_type == "graphsage":
        model = GraphSAGEModel(in_channels, hidden_channels, out_channels).to(device)
        lr = 0.005
        weight_decay = 5e-4
        epochs = 100
    elif model_type == "gatv2":
        # Tuning GATv2: Lower hidden channels, 8 attention heads, higher dropout, lower LR
        model = GATv2Model(in_channels, hidden_channels=8, out_channels=out_channels, heads=8, dropout=0.6).to(device)
        lr = 0.001
        weight_decay = 1e-4
        epochs = 200
    else:
        raise ValueError("Invalid model type. Choose 'graphsage' or 'gatv2'")
        
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    criterion = torch.nn.CrossEntropyLoss()
    
    best_val_f1 = 0.0
    # Use the dynamic epochs defined above
    
    print(f"\n--- Starting {model_type.upper()} Training ---")
    start_time = time.time()
    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        
        # Forward pass on the entire graph
        out = model(data.x, data.edge_index)
        
        # We ONLY calculate loss on the training nodes (Masking prevents label leakage)
        loss = criterion(out[data.train_mask], data.y[data.train_mask])
        loss.backward()
        optimizer.step()
        
        # Validation Phase
        if (epoch+1) % 10 == 0:
            model.eval()
            with torch.no_grad():
                pred = model(data.x, data.edge_index).argmax(dim=1)
                
                # Extract validation predictions and true labels
                val_true = data.y[data.val_mask].cpu().numpy()
                val_pred = pred[data.val_mask].cpu().numpy()
                
                val_acc = accuracy_score(val_true, val_pred)
                val_f1 = f1_score(val_true, val_pred)
                
                print(f"Epoch {epoch+1:03d} | Train Loss: {loss:.4f} | Val Acc: {val_acc:.4f} | Val F1: {val_f1:.4f}")
                
                if val_f1 > best_val_f1:
                    best_val_f1 = val_f1
                    os.makedirs(os.path.join(OUTPUT_DIR, "models"), exist_ok=True)
                    torch.save(model.state_dict(), os.path.join(OUTPUT_DIR, "models", f"best_{model_type}.pt"))
                    
    print(f"Training completed in {time.time() - start_time:.2f} seconds.")
    print(f"Best Validation F1: {best_val_f1:.4f}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=str, default="graphsage", choices=["graphsage", "gatv2"])
    args = parser.parse_args()
    
    train_gnn(args.model)
